### ISSUE TITLE
Support for VS2013

### ISSUE THREAD

**Issue by demianmnave** [user1095108/lualite#1]
Would be great if lualite supported VS2013.  This would require jumping through some hoops to get the forward() functions to work, since VS2013 can't match function signatures against zero-length parameter packs (the typename... A arguments, in particular).  Simpler fixes are needed to avoid using constexpr and noexcept, and to use <X>::value instead of implicit conversions of type_traits <X> classes to bool via the brace constructor syntax.  VS2013 may also have some issues with SFINAE and complex conditionals for enable_if, but I can't experiment more to track those down.

Definitely a nifty library, and I'd use it if I didn't have to support VS2013.

**Comment by user1095108** [comment]
A number of people requested this, but it is never going to happen. I simply don't have the time for it. MSVC2015 is almost here with some C++11/14 support. Maybe lualite will work with that compiler.

**Comment by demianmnave** [comment]
```
Totally understand, thanks for replying.

On 5/27/2015 10:02 AM, janezz55 wrote:


  A number of people requested this, but it is never going to
    happen. I simply don't have the time for it. MSVC2015 is almost
    here with some C++11/14 support. Maybe lualite will work with
    that compiler.
  —
    Reply to this email directly or view
      it on GitHub.
```
